sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t efekaptan/apollo-demo .

script:
  - docker run -e CI=true efekaptan/apollo-demo npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'apollo-demo'
  env: 'ApolloDemo-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-367513523973'
  bucket_path: 'apollo-demo'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY